language: go

go:
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - tip

before_install:
  - sudo apt-get update -y && sudo apt-get install curl grep gawk

install:
  - go get -d -v ./...
  
script:
  - cd key
  - ./get_keycodes.sh /usr/include/linux/input.h
  - echo "using keycodes:" && cat codes.go | grep CODE_
  - go test -v
  - cd ../uinput && go build && go test -c
  - cd ..
  - go build
  - go test -v
